python extract_event.py ^
    --input_root data/data_text ^
    --output_root output/des5 ^
    --datasets MAVEN ACE ^
    --perms 0 1 2 3 4 ^
    --model gemini-2.0-flash ^
    --candidate 5 ^
    --num_try 3 ^
    --max_consecutive_429_error 6 ^
    --max_num_threads 8 ^
    --logs_dir logs/extractor ^
    --eresume ^
    --gen_des